server:
  port: 8130
spring:
  profiles:
    active: dev
  application:
    name: service-oss

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 60000
  sentinel:
    enabled: true